LICENSE.txt
shared/ruckus.tcl

- Updating submodules locks
- Update LICENSE.txt for 2022

Release Candidate v2.1.1

---

petalinux-apps/startupapp/files/startupapp
python/axi_soc_ultra_plus_core/rfsoc_utility/_DacSigGen.py
shared/rtl/AxiSocUltraPlusCore.vhd

- [bring DESC_MEMORY_TYPE_G to top level](https://github.com/slaclab/axi-soc-ultra-plus-core/commit/61a92fe9d81965cf94cf2fb5b4c543b9bc69f377)
- [adding user's runtime Application option](https://github.com/slaclab/axi-soc-ultra-plus-core/commit/7e24044bae2cc4a7eff8807749f9c030c97e4295)
- [adding RefreshDacFsm()](https://github.com/slaclab/axi-soc-ultra-plus-core/commit/cd27aef4bccca6097ddc435611a84522b405ab56)

Release Candidate v2.3.1

---

CreatePetalinuxProject.sh
hardware/XilinxKriaKr260/bd/AxiSocUltraPlusCpuCore.bd
hardware/XilinxKriaKr260/bd/AxiSocUltraPlusCpuCore.tcl
hardware/XilinxKriaKr260/device-tree/system-user.dtsi
hardware/XilinxKriaKr260/ruckus.tcl
hardware/XilinxKriaKr260/xdc/XilinxKriaKr260.xdc
petalinux-apps/rogue.bb
petalinux-apps/runtimeApp
petalinux-apps/startupapp/files/startupapp
python/axi_soc_ultra_plus_core/rfsoc_utility/_RingBufferProcessor.py

- [bug fix for petalinux 2022.1](https://github.com/slaclab/axi-soc-ultra-plus-core/commit/72da85c21876efa311043985ce5b6855deb4eae4)
- [adding XilinxKriaKr260](https://github.com/slaclab/axi-soc-ultra-plus-core/commit/87e2d224a6aed439ec601d89bf666fe96986cab8)
- [bug fix for rogue.bb](https://github.com/slaclab/axi-soc-ultra-plus-core/commit/01110ea095ced33f4e7dc6475d402c34d3611bf4)
- [Adding to juptyer-lab support](https://github.com/slaclab/axi-soc-ultra-plus-core/commit/13b66f505c5dc47ed14c2c3dbed472ec8e06a0d2)
- [adding htop to petalinux](https://github.com/slaclab/axi-soc-ultra-plus-core/commit/1d2d1a79c78d3f7694e8f70e84c2dd2f43c0c673)
- [moving to /u1 for user space partition](https://github.com/slaclab/axi-soc-ultra-plus-core/commit/40699104a9968ee4b6eeff559d5acf42ffb1f254)

Release Candidate v2.4.1

---

hardware/XilinxKriaKv260/ruckus.tcl
hardware/XilinxZcu208/rtl/Hardware.vhd
python/axi_soc_ultra_plus_core/hardware/XilinxZcu208/_Hardware.py

- [switching to .bd file load for Vivado 2022.2 support](https://github.com/slaclab/axi-soc-ultra-plus-core/commit/2d9844865b1fce9d77da395074a99dde727967f3)
- [updating XilinxZcu208/rtl/Hardware.vhd](https://github.com/slaclab/axi-soc-ultra-plus-core/commit/5359eae89bb31d8d896435979655a1b9f0cfdb04)

Release Candidate v2.6.1

---

hardware/XilinxZcu216/xdc/XilinxZcu216.xdc
petalinux-apps/axiversiondump/files/axiversiondump
petalinux-apps/rogue.bb
python/axi_soc_ultra_plus_core/rfsoc_utility/_AppRingBuffer.py
python/axi_soc_ultra_plus_core/rfsoc_utility/_SigGen.py

- [adding pmod pinout to ZCU216](https://github.com/slaclab/axi-soc-ultra-plus-core/pull/18/commits/368f75a435529b9ba34206778f01c69b59262d56)
- [check if non-zero numAdcCh or numDacCh in python for SigGen](https://github.com/slaclab/axi-soc-ultra-plus-core/pull/18/commits/30bffe9525e1a76b9ffbb9620a6be385bada69f3)
- [Misc clean up formating](https://github.com/slaclab/axi-soc-ultra-plus-core/pull/18/commits/fc516023b0547d6d848e73d214e6d4aa8d2da417)
- [upgrading rogue.bb to rogue v5.16.1](https://github.com/slaclab/axi-soc-ultra-plus-core/pull/18/commits/7083a2f3d8c3d257425791e9a7cc1f00d2ccc22e)
- [bug fix for SigGen .CSV loading waveforms](https://github.com/slaclab/axi-soc-ultra-plus-core/pull/18/commits/6bf160a9ab6393b221c6385f6a488dd9ccbf7d01)

Release Candidate v2.7.0

---

python/axi_soc_ultra_plus_core/rfsoc_utility/_SigGen.py
python/axi_soc_ultra_plus_core/rfsoc_utility/gui/_LiveDisplay.py

- [bug fixes for latest PyDM release](https://github.com/slaclab/axi-soc-ultra-plus-core/commit/2e79b4996b122134ae79067b7a21684fb3a4abc9)

Release Candidate v2.7.1

---

LICENSE.txt
hardware/XilinxZcu208/xdc/XilinxZcu208.xdc
hardware/XilinxZcu216/xdc/XilinxZcu216.xdc

- [updating LICENSE.txt for 2023](https://github.com/slaclab/axi-soc-ultra-plus-core/commit/a9e4816c11d3317a61212816a24f22b0cbbf0332)
- [adding plClkP/plSysRefP ports to ZCU208/ZCU216 XDC](https://github.com/slaclab/axi-soc-ultra-plus-core/commit/39658eb954878d559e4b426762459703339bc1d0)

Release Candidate v2.8.0

---

.github/workflows/release_ci.yml
conda-recipe/README.md
conda-recipe/build.sh
conda-recipe/conda_build_config.yaml
conda-recipe/meta.yaml
setup.py

Create Release Package

---

CreatePetalinuxProject.sh
petalinux-apps/python3-p4p/python3-p4p_4.1.5.bb
petalinux-apps/python3-p4p/python3-pvxslibs_1.1.4.bb

- Updates to make the python3-p4p build and run on the Zynq (ARM64)

Update to petalinux/python3-p4p

---

CreatePetalinuxProject.sh
hardware/XilinxKriaKv260/xdc/XilinxKriaKv260.xdc
petalinux-apps/axiversiondump/axiversiondump.bb
petalinux-apps/python3-p4p/python3-epicscorelibs_7.0.7.99.0.0.bb
petalinux-apps/python3-p4p/python3-nose2_0.12.0.bb
petalinux-apps/python3-p4p/python3-p4p_4.1.5.bb
petalinux-apps/python3-p4p/python3-pvxslibs_1.1.4.bb
petalinux-apps/python3-p4p/python3-setuptools-dso_2.7.bb
petalinux-apps/rogue.bb
petalinux-apps/roguetcpbridge/roguetcpbridge.bb
petalinux-apps/startup-app-init/files/startup-app-init
petalinux-apps/startup-app-init/startup-app-init.bb
python/axi_soc_ultra_plus_core/rfsoc_utility/_RingBufferProcessor.py
python/axi_soc_ultra_plus_core/rfsoc_utility/gui/GuiTop.py
python/axi_soc_ultra_plus_core/rfsoc_utility/gui/_LiveDisplay.py

- [MAJOR RELASE CHANGE: Swithcing to /boot directory mount](https://github.com/slaclab/axi-soc-ultra-plus-core/commit/547865d8ffc2a01bd5bc9f3393eedb0868d59491)
- [Checking for SD-Memory[1] mount](https://github.com/slaclab/axi-soc-ultra-plus-core/commit/360e49c097149dfa0a3b0969b72e0106fc98baba)
- Required for KV260
- Updating XilinxKriaKv260.xdc
- Switching from hda to pmod port labeling
- [RingBufferProcessor.py optmization](https://github.com/slaclab/axi-soc-ultra-plus-core/pull/26/commits/c7c2856fe4abc4f50357b9ac78d3d5dc46ffe7b4)
- Added petalinux P4P build support

Release Candidate v3.0.0

---

CreatePetalinuxProject.sh
petalinux-apps/rogue.bb
python/axi_soc_ultra_plus_core/rfsoc_utility/pydm/__init__.py

- [upgrading petalinux to rogue v6.0.0](https://github.com/slaclab/axi-soc-ultra-plus-core/commit/621f1089be24066d3ed9877d9fe9094bafff5167)
- [petalinux version locking to 2022.2](https://github.com/slaclab/axi-soc-ultra-plus-core/commit/3112e31d09f1eba9f67f05154a5d3ce4a78aae32)

Release Candidate v3.4.0

---

hardware/XilinxZcu111/xdc/XilinxZcu111.xdc
python/axi_soc_ultra_plus_core/hardware/RealDigitalRfSoC4x2/_Hardware.py
python/axi_soc_ultra_plus_core/hardware/XilinxZcu111/_Hardware.py
python/axi_soc_ultra_plus_core/rfsoc_utility/_RingBufferProcessor.py
python/axi_soc_ultra_plus_core/rfsoc_utility/_SigGen.py
shared/rfsoc-utility/SigGen/rtl/SigGen.vhd
shared/rfsoc-utility/misc/rtl/SsrToSsr2x.vhd
shared/rfsoc-utility/misc/ruckus.tcl
shared/rfsoc-utility/ruckus.tcl
shared/ruckus.tcl

- updating submodule locks
- Misc bug fixes
- update for LMX in ZCU111 and RFSoC4x2
- adding missing DIFF_TERM for ZCU111
- adding SsrToSsr2x.vhd
- adding NewDataReady variable to RingBufferProcessor.py

Release Candidate v3.6.0

---

hardware/XilinxZcu111/xdc/XilinxZcu111.xdc
python/axi_soc_ultra_plus_core/hardware/XilinxZcu111/_Hardware.py
python/axi_soc_ultra_plus_core/rfsoc_utility/gui/_LiveDisplay.py

- updating XilinxZcu111/_Hardware.py
- bug fix to _LiveDisplay.py
- adding PMOD to XilinxZcu111.xdc

Release Candidate 3.6.1

---

CreatePetalinuxProject.sh

- [adding rfdc arg for bypassing RFDC utility](https://github.com/slaclab/axi-soc-ultra-plus-core/commit/a7d4f04022a0fb8404e275006fadd6aa7cedb703)

Release Candidate 4.2.1

---

petalinux-apps/startup-app-init/files/startup-app-init

- [bug fix for rfsoc 4x2 ETH link bandwidth](https://github.com/slaclab/axi-soc-ultra-plus-core/commit/9f104ca061bff36c3cceec0b028757fd561acd33)
- [adding DMA total buffer size checking](https://github.com/slaclab/axi-soc-ultra-plus-core/commit/7af28720a68e506ec9c0df21737354aec35cc650)
- [fixed bug where SHA256 randomly changes each time the RFSoC boots up](https://github.com/slaclab/axi-soc-ultra-plus-core/commit/f092b80528c7232aa193e15e1a9b8b2b4d1b6c67)

Release Candidate 4.7.0

---

petalinux-apps/pyrfdc/files/PyRFdc.cpp
python/axi_soc_ultra_plus_core/rfsoc_utility/_Rfdc.py
python/axi_soc_ultra_plus_core/rfsoc_utility/_RfdcTile.py

- [migrating all cmd.post() to cmd.set()](https://github.com/slaclab/axi-soc-ultra-plus-core/commit/951aa5f5cd35e4deb5de57c765230927f476fd85)
- [In ResetAll, add an early reset for tiles with PLL enabled](https://github.com/slaclab/axi-soc-ultra-plus-core/commit/91cbaa2f7b0fdb7ab8c93adac2d16bfb16952349)

Release Candidate 5.0.2

---

CreatePetalinuxProject.sh
README.md
hardware/RealDigitalRfSoC4x2/ruckus.tcl
hardware/TrenzTe0835/ruckus.tcl
hardware/XilinxKriaKv260/ruckus.tcl
hardware/XilinxZcu102/ruckus.tcl
hardware/XilinxZcu111/ruckus.tcl
hardware/XilinxZcu208/ruckus.tcl
hardware/XilinxZcu216/ruckus.tcl
hardware/XilinxZcu670/ruckus.tcl
python/axi_soc_ultra_plus_core/rfsoc_utility/_Rfdc.py
shared/rfsoc-utility/AppRingBuffer/ruckus.tcl
shared/rfsoc-utility/SigGen/ruckus.tcl
shared/rfsoc-utility/SigToAxiStream/ruckus.tcl
shared/rfsoc-utility/SsrGearbox/ruckus.tcl
shared/rfsoc-utility/ruckus.tcl
shared/ruckus.tcl

- [adding UpdateIsEnabled() function to _Rfdc.py](https://github.com/slaclab/axi-soc-ultra-plus-core/commit/9c92e3106ecae30effcd74ffaf15b9f8cbb7bf8e)
- [Update README.md to include DOE Code Reference](https://github.com/slaclab/axi-soc-ultra-plus-core/commit/576bf32a32ffbcb726b2cefd420d5839e1ffd454)
- [updating ruckus.tcl to be consistent](https://github.com/slaclab/axi-soc-ultra-plus-core/commit/595b60a2f9f61b7b07c98e52954be620861440e9)
- updating remaining ruckus.tcl files to use the more portable version of loading proc
- #56

Release Candidate 5.1.1

---

petalinux-apps/pyrfdc/files/PyRFdc.cpp
petalinux-apps/pyrfdc/files/PyRFdc.h
petalinux-apps/rogue.bb
python/axi_soc_ultra_plus_core/rfsoc_utility/_Rfdc.py

- [upgrading to rogue v6.6.0](https://github.com/slaclab/axi-soc-ultra-plus-core/pull/60/commits/03521ecc0bedee67dd768f921691e3beea9facfe)
- #58 
- #59

Release Candidate 5.2.0

---

petalinux-apps/pyrfdc/files/PyRFdc.cpp

- Prevent issuing reset to unused TILES

bug fix for global reset when TILE not used

---

petalinux-apps/pyrfdc/files/PyRFdc.cpp
petalinux-apps/rogue.bb

- #61 
- [updating for rogue v6.6.1](https://github.com/slaclab/axi-soc-ultra-plus-core/pull/62/commits/6f453598a8a31a89bd8a5d3baecd8718c7b4784c)

Release Candidate 5.2.1
